name: Publish Docs to GitHub Pages
on: 
  push:
    branches:
      - main


jobs:
  publish-pages:
    name: Publish Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install mdbook
        shell: bash
        run: make install-from-remote

      - name: Build
        shell: bash
        run: ./mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
